[book]
title = "Q/KDB+ Blog"
authors = ["jkane17"]
description = "Blogs for Q/KDB+"
language = "en"

[output.html]
additional-css = ["theme/custom-highlight.css", "theme/navigation.css"]
additional-js = ["theme/navigation.js"]
mathjax-support = true
site-url = "/blog/q/"
